os: linux
language: php
dist: bionic
env:
  global:
    - XDEBUG_MODE=coverage

php:
  - 8.2
  - 8.3

before_script:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/php-coveralls --verbose
